version: 0.2

phases:
  build:
    command:
      - echo Build Starting on `date`
      - chmod -x ./gradlew
      - ./gradlew build
      - cp build/libs/*.jar deploy/application.jar
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - Procfile
    - deploy/application.jar
    - .ebextensions/**/*
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
