version: 0.2

phases:
  build:
    command:
      - echo Build Starting on `date`
      - chmod -x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename deploy/application.jar)
      - cp build/libs/*.jar application.jar
      - pwd

artifacts:
  files:
    - Procfile
    - application.jar
    - .ebextensions/**/*
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
