version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    command:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - mv build/libs/application.jar application.jar
      - pwd

artifacts:
  files:
    - Procfile
    - application.jar
    - .ebextensions/**/*
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
