version: 0.2

phases:
  build:
    command:
      - echo Build Starting on `date`
      - chmod -x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'
