version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - cp build/libs/application.jar application.jar
      - pwd

artifacts:
  files:
    - Procfile
    - application.jar
    - .platform
    - .ebextensions/**/*

cache:
  paths:
    - '/root/.gradle/caches/**/*'
