version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - touch ./src/main/resources/application.properties
      - echo "${spring.h2.console.enabled}" > ./src/main/resources/application.properties
      - echo "${spring.datasource.url}" >> ./src/main/resources/application.properties
      - echo "${spring.datasource.driver-class-name}" >> ./src/main/resources/application.properties
      - echo "${spring.datasource.username}" >> ./src/main/resources/application.properties
      - echo "${spring.datasource.password}" >> ./src/main/resources/application.properties
      - echo "${spring.jpa.database-platform}" >> ./src/main/resources/application.properties
      - cat ./src/main/resources/application.properties
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - cp build/libs/application.jar application.jar
      - pwd

artifacts:
  files:
    - Procfile
    - application.jar
    - .platform
    - .ebextensions/**/*

cache:
  paths:
    - '/root/.gradle/caches/**/*'
