INSERT INTO CATEGORY (CATEGORY_ID , NAME) VALUES (1, '테니스');
INSERT INTO CATEGORY (CATEGORY_ID , NAME) VALUES (2, '축구');
INSERT INTO CATEGORY (CATEGORY_ID , NAME) VALUES (3, '농구');
INSERT INTO CATEGORY (CATEGORY_ID , NAME) VALUES (4, '배드민턴');
