# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ "savannah/feature/14" ]
  pull_request:
    branches: [ "savannah/feature/14" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: | 
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys:
            ${{runner.os}}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: make application.yml
        run:
          mkdir ./src/main/resources |
          touch ./src/main/resources/application.yml
        shell: bash

      - name: deliver application.yml
        run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Test with Gradle
        run: ./gradlew --info test

      # Object Storage에 업로드할 파일만 모을 server 디렉터리 생성
      - name: make server directory
        run:  mkdir -p server

      # 1. Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./server

      # 3. script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./server

      # 파일 압축
      - name: Make zip file and move to server directory
        run: zip -r ./wontu-webserver.zip ./server

      # S3에 업로드
      - name: upload build file to NCP Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws --endpoint-url=https://kr.object.ncloudstorage.com \
          s3 cp ./wontu-webserver.zip \
          --region ap-northeast-2 \
          s3://wontu-object-storage-bucket

      # makeSignature 함수 실행 결과물을 TIMESTAMP,SIGNATURE 변수에 저장
      - name: make signature and extract variables
        run: |
          chmod +x ./makeSignature.sh 
          OUTPUT=$(./makeSignature.sh secrets.NCP_ACCESS_KEY_ID_DEPLOY secrets.NCP_SECRET_ACCESS_KEY_DEPLOY)
          echo ${{OUTPUT}}
          echo "TIMESTAMP=$(echo ${OUTPUT})" >> $GITHUB_OUTPUT
          echo "TIMESTAMP2=1505290625682" >> $GITHUB_OUTPUT
          echo "TIMESTAMP3='1505290625682'" >> $GITHUB_OUTPUT
          echo "SIGNATURE=$(echo ${OUTPUT[2]})" >> $GITHUB_OUTPUT
        id: extract

      - name: request deploy
        run: |
          echo ${{ steps.extract.outputs.TIMESTAMP1 }}
          echo ${{ steps.extract.outputs.TIMESTAMP2 }}
          echo ${{ steps.extract.outputs.TIMESTAMP3 }}
          echo $((${{ steps.extract.outputs.SIGNATURE }}))
          curl -i -X GET \
          -H "x-ncp-apigw-timestamp:"${{ steps.extract.outputs.TIMESTAMP }} \
          -H "x-ncp-iam-access-key:"${{ secrets.NCP_ACCESS_KEY_ID_DEPLOY }} \
          -H "x-ncp-apigw-signature-v2:"${{ steps.extract.outputs.SIGNATURE}} \
          'https://sourcedeploy.apigw.ntruss.com/api/v1/project'
